// Generated by gencpp from file mujoco_ros_msgs/SensorBase.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_SENSORBASE_H
#define MUJOCO_ROS_MSGS_MESSAGE_SENSORBASE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mujoco_ros_msgs
{
template <class ContainerAllocator>
struct SensorBase_
{
  typedef SensorBase_<ContainerAllocator> Type;

  SensorBase_()
    : name()
    , data()  {
    }
  SensorBase_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::mujoco_ros_msgs::SensorBase_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mujoco_ros_msgs::SensorBase_<ContainerAllocator> const> ConstPtr;

}; // struct SensorBase_

typedef ::mujoco_ros_msgs::SensorBase_<std::allocator<void> > SensorBase;

typedef boost::shared_ptr< ::mujoco_ros_msgs::SensorBase > SensorBasePtr;
typedef boost::shared_ptr< ::mujoco_ros_msgs::SensorBase const> SensorBaseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mujoco_ros_msgs::SensorBase_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mujoco_ros_msgs::SensorBase_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mujoco_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mujoco_ros_msgs': ['/home/saga/mujoco_ws/src/mujoco_ros_sim/mujoco_ros_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::SensorBase_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::SensorBase_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::SensorBase_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::SensorBase_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::SensorBase_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::SensorBase_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mujoco_ros_msgs::SensorBase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de229af6c922862f640c59218b71e019";
  }

  static const char* value(const ::mujoco_ros_msgs::SensorBase_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde229af6c922862fULL;
  static const uint64_t static_value2 = 0x640c59218b71e019ULL;
};

template<class ContainerAllocator>
struct DataType< ::mujoco_ros_msgs::SensorBase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/SensorBase";
  }

  static const char* value(const ::mujoco_ros_msgs::SensorBase_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mujoco_ros_msgs::SensorBase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
\n\
float64[] data\n\
";
  }

  static const char* value(const ::mujoco_ros_msgs::SensorBase_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mujoco_ros_msgs::SensorBase_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorBase_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mujoco_ros_msgs::SensorBase_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mujoco_ros_msgs::SensorBase_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_SENSORBASE_H
